directive @generateUDFResolvers on FIELD_DEFINITION | OBJECT
type Ingredient @generateUDFResolvers{
  id: ID!
  name: String!
  price: Float!
  lossPercent: Int!
  unitMeasure: UnitOfMeasurement!
  packPrice: Int!
  packSize: Float!
}

enum UnitOfMeasurement {
  KILOGRAM
  POUND
  LITER
  GRAM
}

input IngredientInput {
  name: String!
  unitMeasure: UnitOfMeasurement!
  price: Float!
  lossPercent: Int
}