directive @generateUDFResolvers on FIELD_DEFINITION | OBJECT
type Ingredient @generateUDFResolvers{
  id: ID!
  name: String!
  unitPrice: Int!
  unitAmount: Int!
  lossPercent: Int!
  unitMeasure: UnitOfMeasurement!
}

enum UnitOfMeasurement {
  KILOGRAM
  POUND
  LITER
  GRAM
}

input IngredientInput {
  ingredient: ID!
  unitMeasure: UnitOfMeasurement!
  price: Float!
}