type IngredientAmount {
  id: ID!
  ingredient: Ingredient!
  amount: Int!
  unitMeasure: UnitOfMeasurement!
  recipe: Recipe!
}

input IngredientAmountInput {
  ingredient: RecipeAmountIngredientInput!
  amount: Int!
  unitMeasure: UnitOfMeasurement!
  recipe: RecipeIngredientInput!
}

input RecipeAmountIngredientInput {
  id: String!
}

input RecipeIngredientInput {
  id: String!
}