type Recipe {
  id: ID!
  user: User!
  name: String!
  ingredientAmounts: [IngredientAmount!]
}

input RecipeInput {
  name: String!
  user: RecipeUserInput
}

input RecipeUserInput {
  id: String!
}